// Code generated by MockGen. DO NOT EDIT.
// Source: task.go
//
// Generated by this command:
//
//	mockgen -source=task.go -destination=mocks/mock_db.go -package=mocks DB
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	tasks "dns/internal/tasks"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// DequeueTasks mocks base method.
func (m *MockDB) DequeueTasks(ctx context.Context, batchSize int) ([]tasks.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DequeueTasks", ctx, batchSize)
	ret0, _ := ret[0].([]tasks.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DequeueTasks indicates an expected call of DequeueTasks.
func (mr *MockDBMockRecorder) DequeueTasks(ctx, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DequeueTasks", reflect.TypeOf((*MockDB)(nil).DequeueTasks), ctx, batchSize)
}

// GetTaskEvents mocks base method.
func (m *MockDB) GetTaskEvents(ctx context.Context, taskID int64) ([]tasks.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskEvents", ctx, taskID)
	ret0, _ := ret[0].([]tasks.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskEvents indicates an expected call of GetTaskEvents.
func (mr *MockDBMockRecorder) GetTaskEvents(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskEvents", reflect.TypeOf((*MockDB)(nil).GetTaskEvents), ctx, taskID)
}

// GetTaskStatus mocks base method.
func (m *MockDB) GetTaskStatus(ctx context.Context, id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskStatus", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskStatus indicates an expected call of GetTaskStatus.
func (mr *MockDBMockRecorder) GetTaskStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskStatus", reflect.TypeOf((*MockDB)(nil).GetTaskStatus), ctx, id)
}

// ReaperUpdateStatusFailed mocks base method.
func (m *MockDB) ReaperUpdateStatusFailed(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReaperUpdateStatusFailed", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReaperUpdateStatusFailed indicates an expected call of ReaperUpdateStatusFailed.
func (mr *MockDBMockRecorder) ReaperUpdateStatusFailed(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReaperUpdateStatusFailed", reflect.TypeOf((*MockDB)(nil).ReaperUpdateStatusFailed), ctx)
}

// ReaperUpdateStatusQueued mocks base method.
func (m *MockDB) ReaperUpdateStatusQueued(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReaperUpdateStatusQueued", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReaperUpdateStatusQueued indicates an expected call of ReaperUpdateStatusQueued.
func (mr *MockDBMockRecorder) ReaperUpdateStatusQueued(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReaperUpdateStatusQueued", reflect.TypeOf((*MockDB)(nil).ReaperUpdateStatusQueued), ctx)
}

// StoreTask mocks base method.
func (m *MockDB) StoreTask(ctx context.Context, task tasks.StoreTaskReq) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTask", ctx, task)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreTask indicates an expected call of StoreTask.
func (mr *MockDBMockRecorder) StoreTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTask", reflect.TypeOf((*MockDB)(nil).StoreTask), ctx, task)
}

// UpdateTaskStatusFailed mocks base method.
func (m *MockDB) UpdateTaskStatusFailed(ctx context.Context, id int64, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatusFailed", ctx, id, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatusFailed indicates an expected call of UpdateTaskStatusFailed.
func (mr *MockDBMockRecorder) UpdateTaskStatusFailed(ctx, id, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatusFailed", reflect.TypeOf((*MockDB)(nil).UpdateTaskStatusFailed), ctx, id, lastError)
}

// UpdateTaskStatusSucceeded mocks base method.
func (m *MockDB) UpdateTaskStatusSucceeded(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatusSucceeded", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatusSucceeded indicates an expected call of UpdateTaskStatusSucceeded.
func (mr *MockDBMockRecorder) UpdateTaskStatusSucceeded(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatusSucceeded", reflect.TypeOf((*MockDB)(nil).UpdateTaskStatusSucceeded), ctx, id)
}
